const fs = require('fs');

const topics = [
  { p1: "Work", p2: "favorite season of the year", p3: "Climate and weather changes" },
  { p1: "Study", p2: "public place that you think needs improvements", p3: "Public facilities and parks" },
  { p1: "Hometown", p2: "city or country you want to live the most in the future", p3: "Living abroad vs living in your hometown" },
  { p1: "Home", p2: "something you learned in a place or from a person", p3: "Education and learning methods" },
  { p1: "Art", p2: "occasion where you received a good service from a company or shop", p3: "Customer service and business" },
  { p1: "Birthdays", p2: "toy that you received when you were a child", p3: "Toys and child development" },
  { p1: "Clothes", p2: "famous person that you are interested in", p3: "Celebrities and their influence" },
  { p1: "Daily Routine", p2: "photo you have taken", p3: "Photography and social media" },
  { p1: "Dictionaries", p2: "interesting event in your school", p3: "School events and education" },
  { p1: "Evenings", p2: "situation where you have to be polite", p3: "Politeness and manners in society" },
  { p1: "Family & Friends", p2: "visitor in your home", p3: "Hospitality and guests" },
  { p1: "Food", p2: "place in your city you want to go to", p3: "Tourism and city attractions" },
  { p1: "Hobbies", p2: "important river/lake in your country", p3: "Water resources and activities" },
  { p1: "Internet", p2: "person you know", p3: "Friendship and relationships" },
  { p1: "Leisure Time", p2: "impressive story you heard from other people", p3: "Storytelling and reading" },
  { p1: "Music", p2: "recent development in your city", p3: "City development and infrastructure" },
  { p1: "Neighbours & Neighbourhood", p2: "unforgettable dinner", p3: "Eating habits and restaurants" },
  { p1: "Newspapers", p2: "historical era you are interested in", p3: "History and its importance" },
  { p1: "Pets", p2: "special day out", p3: "Saving money and free time" },
  { p1: "Reading", p2: "sports person you admire", p3: "Sports and physical education" },
  { p1: "Shopping", p2: "experience where you were late for an event", p3: "Punctuality and time management" },
  { p1: "Sport", p2: "piece of technology you like using except computers", p3: "Technology and its impact" },
  { p1: "TV", p2: "something special that you saved money to buy", p3: "Saving money and shopping" },
  { p1: "Transport", p2: "holiday you would like to take in the future", p3: "Tourism and holidays" },
  { p1: "Weather", p2: "someone who is a good parent", p3: "Parenting and family" },
  { p1: "Work", p2: "rule at your school that you agree or disagree with", p3: "School rules and education" },
  { p1: "Study", p2: "achievement that you are proud of", p3: "Success and goals" },
  { p1: "Hometown", p2: "car journey you went on", p3: "Traveling by car and transport" },
  { p1: "Home", p2: "something you bought recently that made you happy", p3: "Shopping and happiness" },
  { p1: "Art", p2: "dream house or apartment you want to live in", p3: "Housing and accommodation" },
  { p1: "Birthdays", p2: "activity you do to keep fit", p3: "Health and fitness" },
  { p1: "Clothes", p2: "science subject you learned in your school", p3: "Science and education" },
  { p1: "Daily Routine", p2: "difficult decision that you once made", p3: "Decision making and choices" },
  { p1: "Dictionaries", p2: "garden/park you have visited", p3: "Parks and public spaces" },
  { p1: "Evenings", p2: "occasion where somebody gave you positive suggestions", p3: "Advice and suggestions" },
  { p1: "Family & Friends", p2: "occasion when you helped a person", p3: "Helping others and volunteering" },
  { p1: "Food", p2: "traditional product in your country", p3: "Traditions and culture" },
  { p1: "Hobbies", p2: "leisure facility you would like to have in your home town", p3: "Leisure facilities and free time" },
  { p1: "Internet", p2: "place people can listen to music", p3: "Music and entertainment" },
  { p1: "Leisure Time", p2: "piece of furniture you like", p3: "Furniture and home decoration" },
  { p1: "Music", p2: "important letter you received", p3: "Letters and communication" },
  { p1: "Neighbours & Neighbourhood", p2: "exciting book you have read", p3: "Reading and literature" },
  { p1: "Newspapers", p2: "interesting person from another country", p3: "Foreigners and culture" },
  { p1: "Pets", p2: "businessman that you admire", p3: "Business and success" },
  { p1: "Reading", p2: "experience that you taught a friend or a relative", p3: "Teaching and learning" },
  { p1: "Shopping", p2: "interesting place that few tourists visit", p3: "Tourism and travel" },
  { p1: "Sport", p2: "something you bought according to an advertisement", p3: "Advertising and consumerism" },
  { p1: "TV", p2: "time you felt happy that you used your cellphone", p3: "Cellphones and communication" },
  { p1: "Transport", p2: "person who knows a lot", p3: "Knowledge and learning" },
  { p1: "Weather", p2: "advertisement you have seen recently", p3: "Advertising and media" },
  { p1: "Work", p2: "TV program", p3: "Television and media" },
  { p1: "Study", p2: "something you enjoy doing with an old person in your family", p3: "Elderly people and family" },
  { p1: "Hometown", p2: "unusual dinner that you had", p3: "Food and dining" },
  { p1: "Home", p2: "important event that you celebrated", p3: "Celebrations and events" },
  { p1: "Art", p2: "important skill which cannot be learned at school", p3: "Skills and education" },
  { p1: "Birthdays", p2: "couple you know who have a happy marriage", p3: "Marriage and relationships" },
  { p1: "Clothes", p2: "helpful person at work or school", p3: "Helping others and teamwork" },
  { p1: "Daily Routine", p2: "new friend you've made recently", p3: "Friendship and socializing" },
  { p1: "Dictionaries", p2: "polite person you met", p3: "Politeness and manners" },
  { p1: "Evenings", p2: "family member who has had an important influence on you", p3: "Family and influence" },
  { p1: "Family & Friends", p2: "invention that changed people's lives", p3: "Inventions and technology" },
  { p1: "Food", p2: "favourite piece of clothing", p3: "Clothes and fashion" },
  { p1: "Hobbies", p2: "city or town you have been to", p3: "Cities and travel" },
  { p1: "Internet", p2: "place you visited", p3: "Travel and tourism" },
  { p1: "Leisure Time", p2: "cafe you like or dislike", p3: "Cafes and restaurants" },
  { p1: "Music", p2: "lesson that you enjoyed", p3: "Education and learning" },
  { p1: "Neighbours & Neighbourhood", p2: "leisure activity near or on the sea", p3: "Water activities and free time" },
  { p1: "Newspapers", p2: "service from a company or shop", p3: "Customer service and business" },
  { p1: "Pets", p2: "interesting conversation you had with someone", p3: "Communication and socializing" },
  { p1: "Reading", p2: "change in your life", p3: "Life changes and personal growth" },
  { p1: "Shopping", p2: "time when you worked in a team", p3: "Teamwork and collaboration" },
  { p1: "Sport", p2: "piece of good news you heard", p3: "Good news and communication" },
  { p1: "TV", p2: "trip you took by bike", p3: "Bicycles and transport" },
  { p1: "Transport", p2: "decision that you disagreed with", p3: "Decisions and opinions" },
  { p1: "Weather", p2: "enjoyable experience you had in the countryside", p3: "Countryside and nature" },
  { p1: "Work", p2: "type of weather you like", p3: "Weather and climate" },
  { p1: "Study", p2: "interesting talk or speech you heard", p3: "Public speaking and communication" },
  { p1: "Hometown", p2: "experience when you spent time with a child", p3: "Children and parenting" },
  { p1: "Home", p2: "piece of artwork that you have seen before", p3: "Art and creativity" },
  { p1: "Art", p2: "useful website that you often visit", p3: "Internet and technology" },
  { p1: "Birthdays", p2: "one of your best friends", p3: "Friendship and character" },
  { p1: "Clothes", p2: "street you know well", p3: "City life and places" },
  { p1: "Daily Routine", p2: "time when you saw an interesting animal", p3: "Animals and wildlife" },
  { p1: "Dictionaries", p2: "famous person that you are interested in", p3: "Fame and success" },
  { p1: "Evenings", p2: "interesting neighbour you know", p3: "Neighbours and community" },
  { p1: "Family & Friends", p2: "family member that made you proud", p3: "Family and pride" },
  { p1: "Food", p2: "two people from the same family", p3: "Family relations and traits" },
  { p1: "Hobbies", p2: "important plant in your country", p3: "Plants and environment" },
  { p1: "Internet", p2: "foreign food you would like to try", p3: "International cuisine and travel" },
  { p1: "Leisure Time", p2: "crowded place", p3: "City places and people" },
  { p1: "Music", p2: "popular place", p3: "Popularity and locations" },
  { p1: "Neighbours & Neighbourhood", p2: "newly-opened shop", p3: "Shopping and consumerism" },
  { p1: "Newspapers", p2: "place where you want to work", p3: "Workplaces and career" },
  { p1: "Pets", p2: "time that you arrived early", p3: "Punctuality and habits" },
  { p1: "Reading", p2: "interesting event", p3: "Events and activities" },
  { p1: "Shopping", p2: "plan you have made", p3: "Planning and future goals" },
  { p1: "Sport", p2: "special trip in the near future", p3: "Travel and holidays" },
  { p1: "TV", p2: "kind of music or a song", p3: "Music and art" },
  { p1: "Transport", p2: "time when you were not allowed to use your cell phone", p3: "Technology and rules" },
  { p1: "Weather", p2: "TV series you enjoy watching", p3: "Television and entertainment" },
  { p1: "Work", p2: "interesting advertisement", p3: "Advertisements and media" },
  { p1: "Study", p2: "someone you admire who is much older than you", p3: "Age and admiration" },
  { p1: "Hometown", p2: "person who has apologized to you", p3: "Apologies and relationships" },
  { p1: "Home", p2: "dinner you enjoyed with your friends", p3: "Food and socializing" },
  { p1: "Art", p2: "time when you had to work hard to achieve a goal", p3: "Goals and hard work" },
  { p1: "Birthdays", p2: "holiday or vacation you have been on", p3: "Holidays and travel" },
  { p1: "Clothes", p2: "happy family event that you remember well", p3: "Family and celebrations" },
  { p1: "Daily Routine", p2: "long journey you travelled by car", p3: "Journeys and transport" },
  { p1: "Dictionaries", p2: "short trip that was special to you", p3: "Short trips and memories" },
  { p1: "Evenings", p2: "environment law", p3: "Environment and law" },
  { p1: "Family & Friends", p2: "recent happy event", p3: "Happiness and events" },
  { p1: "Food", p2: "long walk you had", p3: "Walking and health" },
  { p1: "Hobbies", p2: "situation when someone made noise", p3: "Noise and living environments" },
  { p1: "Internet", p2: "difficult choice that you made", p3: "Choices and decisions" },
  { p1: "Leisure Time", p2: "what you would do if you were given a day off", p3: "Free time and leisure" },
  { p1: "Music", p2: "ideal house", p3: "Housing and architecture" },
  { p1: "Neighbours & Neighbourhood", p2: "book you liked to read in your childhood", p3: "Books and childhood" },
  { p1: "Newspapers", p2: "success in your life", p3: "Success and achievements" },
  { p1: "Pets", p2: "time when you were looking at the sky", p3: "Nature and the sky" },
  { p1: "Reading", p2: "article you read about healthy life", p3: "Health and lifestyle" },
  { p1: "Shopping", p2: "new skill you would like to learn", p3: "Skills and learning" },
  { p1: "Sport", p2: "one activity stopped by the weather", p3: "Weather and activities" },
  { p1: "TV", p2: "person who gave a clever solution to a problem", p3: "Problems and solutions" },
  { p1: "Transport", p2: "time when you had a problem with a piece of equipment", p3: "Equipment and technology" },
  { p1: "Weather", p2: "outdoor meal or picnic that you had", p3: "Meals and outdoors" },
  { p1: "Work", p2: "project or a piece of work you did together with someone", p3: "Projects and teamwork" },
  { p1: "Study", p2: "important stage of your life", p3: "Life stages and development" },
  { p1: "Hometown", p2: "occasion that someone or something made noise", p3: "Noise and nuisance" },
  { p1: "Home", p2: "something you do to keep healthy", p3: "Health and habits" },
  { p1: "Art", p2: "something that makes you excited", p3: "Excitement and emotions" },
  { p1: "Birthdays", p2: "experience that you had when you left home", p3: "Leaving home and independence" },
  { p1: "Clothes", p2: "positive change that you made to your life", p3: "Changes and life" },
  { p1: "Daily Routine", p2: "person you know who is beautiful or handsome", p3: "Appearance and people" },
  { p1: "Dictionaries", p2: "old friend you enjoy talking with", p3: "Friendship and communication" },
  { p1: "Evenings", p2: "place where people go to listen to music", p3: "Music and places" },
  { p1: "Family & Friends", p2: "shop that has opened in your hometown", p3: "Shops and towns" },
  { p1: "Food", p2: "movie you would like to watch again", p3: "Movies and cinema" },
  { p1: "Hobbies", p2: "subject you would like to study that you never had the opportunity to study", p3: "Subjects and education" },
  { p1: "Internet", p2: "memorable story told by someone", p3: "Stories and memories" },
  { p1: "Leisure Time", p2: "art and craft activity you did at school", p3: "Art and school" }
];

let content = `import { Scenario } from './scenarios';\n\nexport const generatedIeltsScenarios: Scenario[] = [\n`;

topics.forEach((t, i) => {
  const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
  content += `  {
    id: "ielts_gen_${i + 1}",
    category: "IELTS Preparation",
    title: "IELTS Mock: ${t.p1} & ${cap(t.p2)}",
    level: "B1-B2",
    role: "default",
    topic: "You are an official, highly strict IELTS Speaking Examiner conducting a full mock test. Be highly critical and objective in your evaluation.",
    icebreaker: "Hello. Let's start with Part 1. Let's talk about ${t.p1.toLowerCase()}. What can you tell me about that?",
    vocabulary: ["IELTS", "Speaking", "Fluency", "Vocabulary", "Grammar"],
    studentBriefing: "Full IELTS Mock Test. Part 1: ${t.p1}. Part 2: Describe a ${t.p2}. Part 3: ${t.p3}.",
    objective: \`STRICT SCENARIO INSTRUCTIONS:
Conduct a full IELTS Speaking test step-by-step.
- Part 1 (${t.p1}): Ask 2-3 questions one by one. Wait for answers.
- Part 2 (Cue Card): "Now I will give you a topic. Describe a ${t.p2}. You should say what it is, when it was, and explain why it is important to you." Wait for the user's full response.
- Part 3 (${t.p3}): Ask 2-3 deep, abstract questions related to the topic.
- Conclude the test and give a highly critical, strictly objective estimated band score. Do not inflate scores.\`
  },\n`;
});

content += `];\n`;

fs.writeFileSync('src/lib/generated_scenarios.ts', content);
console.log('Generated ' + topics.length + ' scenarios.');
